# Second dataset

## Get Data

In [1]:
import pandas as pd

In [2]:
dfcsv = pd.read_csv("../Twitter_Data.csv")

In [3]:
dfcsv.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [4]:
dfcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   clean_text  162976 non-null  object 
 1   category    162973 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.5+ MB


In [5]:
dfcsv.isnull().sum()

clean_text    4
category      7
dtype: int64

## Data cleansing

In [6]:
import tensorflow as tf
import numpy as np
import re

2023-02-27 11:12:07.006170: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-27 11:12:07.407967: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-27 11:12:07.537941: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-27 11:12:07.537962: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if yo

### Remove null values 

In [7]:
dfcsv.dropna(inplace=True) # removes rows with null values

In [8]:
dfcsv.isnull().sum()

clean_text    0
category      0
dtype: int64

In [9]:
import re
# Same cleaning function as other dataset
def clean_data(text):
    # Removing mentions
    text = re.sub(r"/b@","",text)
        
    # Remove links
    text = re.sub(r"(?:\@|https?\://)\S+", "", text)
    
    # Remove digits & strings of digits
    text = re.sub(r"([0-9])","",text)
    
    # Remove new lines
    text = re.sub(r"\n","",text)
    
    # Removes all punctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    
    return text

In [10]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(clean_data)

In [11]:
dfcsv.head()

clean_text  category
0  when modi promised minimum government maximum ...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

## Lowercase text

In [12]:
def lowercase_data(data):
    data = data.lower()
    return data

In [13]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lowercase_data)

In [14]:
dfcsv.head(10)

clean_text  category
0  when modi promised minimum government maximum ...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0
5           kiya tho refresh maarkefir comment karo        0.0
6  surat women perform yagna seeks divine grace f...       0.0
7  this comes from cabinet which has scholars lik...       0.0
8  with upcoming election india saga going import...       1.0
9                         gandhi was gay does modi         1.0

## Remove emojis

In [15]:
def remove_emoji(data):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  #face emojis
                           u"\U0001F300-\U0001F5FF"  #symbols
                           u"\U0001F680-\U0001F6FF"  #transport & map emojis
                           u"\U0001F1E0-\U0001F1FF"  # flags
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', data)

In [16]:
remove_emoji("🇬🇧")

''

In [17]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lowercase_data)

In [18]:
dfcsv.head(10)

clean_text  category
0  when modi promised minimum government maximum ...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0
5           kiya tho refresh maarkefir comment karo        0.0
6  surat women perform yagna seeks divine grace f...       0.0
7  this comes from cabinet which has scholars lik...       0.0
8  with upcoming election india saga going import...       1.0
9                         gandhi was gay does modi         1.0

## Remove Stop words

In [19]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /home/adamo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
from nltk.corpus import stopwords
stopwords = stopwords.words("english")

In [21]:
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [22]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lambda words: ' '.join([word for word in words.split() if word not in (stopwords)]))
# Using lamba to have a neat inline function, also works better than using a written function

In [23]:
dfcsv.head(10)

clean_text  category
0  modi promised minimum government maximum gover...      -1.0
1             talk nonsense continue drama vote modi       0.0
2  say vote modi welcome bjp told rahul main camp...       1.0
3  asking supporters prefix chowkidar names modi ...       1.0
4  answer among powerful world leader today trump...       1.0
5            kiya tho refresh maarkefir comment karo       0.0
6  surat women perform yagna seeks divine grace n...       0.0
7  comes cabinet scholars like modi smriti hema t...       0.0
8  upcoming election india saga going important p...       1.0
9                                    gandhi gay modi       1.0

## Removing non enlgish words

In [24]:
nltk.download("words")

[nltk_data] Downloading package words to /home/adamo/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [25]:
Allwords = set(nltk.corpus.words.words())

In [26]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lambda w: ' '.join([ws for ws in w.split() if ws in (Allwords) or not ws.isalpha()]))

In [27]:
dfcsv.head(10)

clean_text  category
0  minimum government maximum governance begin di...      -1.0
1                  talk nonsense continue drama vote       0.0
2  say vote welcome told main campaigner think relax       1.0
3  prefix great service confusion read crustal cl...       1.0
4  answer among powerful world leader today trump...       1.0
5                           tho refresh comment karo       0.0
6                  surat perform divine grace become       0.0
7          comes cabinet like smriti time introspect       0.0
8  upcoming election saga going important pair lo...       1.0
9                                                gay       1.0

## Lemmatization

In [28]:
import nltk 
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to /home/adamo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/adamo/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [29]:
from nltk.stem import WordNetLemmatizer

In [30]:
lemmatizer = WordNetLemmatizer()

In [31]:
print(lemmatizer.lemmatize("dogs"))
print(lemmatizer.lemmatize("phones"))

dog
phone


In [32]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lemmatizer.lemmatize)

In [33]:
dfcsv.head(10)

clean_text  category
0  minimum government maximum governance begin di...      -1.0
1                  talk nonsense continue drama vote       0.0
2  say vote welcome told main campaigner think relax       1.0
3  prefix great service confusion read crustal cl...       1.0
4  answer among powerful world leader today trump...       1.0
5                           tho refresh comment karo       0.0
6                  surat perform divine grace become       0.0
7          comes cabinet like smriti time introspect       0.0
8  upcoming election saga going important pair lo...       1.0
9                                                gay       1.0

## Encoding the label

In [34]:
def sentiment_encoder(data):
    if data == -1.0:
        data = 0
    elif data == 1.0:
        data = 2
    elif data == 0:
        data = 1
    else:
        data = None
        
    return data

In [35]:
dfcsv["category"] = dfcsv["category"].apply(sentiment_encoder)

In [36]:
dfcsv.head()

clean_text  category
0  minimum government maximum governance begin di...         0
1                  talk nonsense continue drama vote         1
2  say vote welcome told main campaigner think relax         2
3  prefix great service confusion read crustal cl...         2
4  answer among powerful world leader today trump...         2

In [37]:
dfcsv.isnull().sum()

clean_text    0
category      0
dtype: int64

## Split data into training and testing

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
# Test size is 30% of total data from data set
x_train, x_test, y_train, y_test = train_test_split(dfcsv["clean_text"].values, dfcsv["category"].values,
                                                    test_size=0.3)

# Checking the sentiment has been split up appropriately 
print('sentiment Text: ', x_train[2])
print('sentiment: ', y_train[2])

sentiment Text:  big idiot jealous person happy thing good
sentiment:  0


## Tokenizing data

In [40]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [41]:
tokenizer = Tokenizer(num_words=100000000)
totalWords = [*x_train, *x_test]
tokenizer.fit_on_texts(totalWords)

In [42]:
wordindex = tokenizer.word_index
VocabSize= len(wordindex)
print("The number of unique words is: ", VocabSize)

The number of unique words is:  17954


In [43]:
print(wordindex)

{'people': 1, 'congress': 2, 'like': 3, 'one': 4, 'vote': 5, 'dont': 6, 'country': 7, 'election': 8, 'time': 9, 'even': 10, 'nation': 11, 'also': 12, 'know': 13, 'government': 14, 'get': 15, 'power': 16, 'want': 17, 'minister': 18, 'give': 19, 'good': 20, 'space': 21, 'would': 22, 'said': 23, 'money': 24, 'see': 25, 'done': 26, 'credit': 27, 'party': 28, 'make': 29, 'sir': 30, 'prime': 31, 'every': 32, 'think': 33, 'say': 34, 'take': 35, 'back': 36, 'never': 37, 'work': 38, 'support': 39, 'opposition': 40, 'via': 41, 'new': 42, 'many': 43, 'need': 44, 'come': 45, 'made': 46, 'today': 47, 'poor': 48, 'please': 49, 'world': 50, 'last': 51, 'great': 52, 'much': 53, 'media': 54, 'may': 55, 'anti': 56, 'right': 57, 'win': 58, 'news': 59, 'leader': 60, 'first': 61, 'political': 62, 'well': 63, 'still': 64, 'day': 65, 'best': 66, 'going': 67, 'live': 68, 'satellite': 69, 'better': 70, 'mission': 71, 'man': 72, 'way': 73, 'family': 74, 'cant': 75, 'got': 76, 'must': 77, 'given': 78, 'nothing':

In [44]:
import json
fileToDump = open("Embeddings.json","w")

json.dump(wordindex,fileToDump)

fileToDump.close()

In [45]:
len(x_test)

48891

In [46]:
train_seq = tokenizer.texts_to_sequences(x_train) # Compares all the data to vocab and assigns a integer reference for the vocab 
test_seq = tokenizer.texts_to_sequences(x_test)
print(test_seq)

[[945, 381, 2236, 1584, 450, 945, 381, 2236, 1584, 5603, 419], [160, 537, 1462, 678, 197, 2866, 17, 1223, 1142, 1544, 1142, 250, 1810], [20, 119, 45, 1520, 9206, 1648, 45, 379, 174, 122, 1525, 232, 535, 921, 5595, 148], [267, 32, 706, 146, 7310, 60, 107, 7, 306, 16646, 979], [151, 146, 282, 125, 14], [11, 51, 1308, 173, 2, 110, 95, 607, 2739, 1945, 11, 4365, 181, 176, 24, 173, 1263, 22, 1319, 272, 173, 2], [48, 347, 77, 34, 297, 15, 331, 262, 2, 262, 878, 146, 277], [85, 1100, 3242, 798, 61], [377, 1095, 660, 22, 3, 140, 237, 1, 1341, 1602, 202, 36, 553, 977, 16647, 38], [778, 59], [8, 9, 35, 377, 20, 851], [2, 140, 2436, 211, 44, 2442, 39, 105, 78, 1373, 13], [264, 1031], [34], [193, 242, 161, 515, 152, 233, 9, 792, 588, 24, 171, 4540, 5292, 1543, 5107, 2886, 3393, 167], [31, 18, 309], [807, 4676, 700, 109, 417, 7, 1396, 207, 3027, 963, 431], [86, 394, 5327, 259, 384, 2224, 681, 622, 163, 2433], [13, 1840, 4746, 3, 1612, 1840, 4746], [302, 3358, 544, 6, 4667, 124, 231, 249, 3701, 685,

In [47]:
len(test_seq)

48891

In [48]:
from tensorflow.keras.preprocessing.sequence import pad_sequences 

In [49]:
# PAD sequences so they are all the same length as the inputs must all be of same length

train_padded = pad_sequences(train_seq)

print(train_padded[0])

# Check size of each padded sequence

TrainingPadShape = train_padded.shape[1] # for use when defining the model shape 
print(TrainingPadShape)

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0  40 505 342]
31


In [50]:
test_padded = pad_sequences(test_seq,maxlen=TrainingPadShape)
print(test_padded.shape[1])

31


In [51]:
print(y_train)

[2 2 0 ... 1 0 0]


# Data changes

In [52]:
from keras.utils import to_categorical

In [53]:
y_train = to_categorical(y_train, 3)
y_test = to_categorical(y_test, 3)

In [54]:
print(y_train)

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## Constructing the model

In [55]:
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, GlobalMaxPooling1D
from tensorflow.keras.models import Model

In [56]:
DimentionEmbeddingLayer = 10
DimentionLSTMLayer = 30

inputLayer = Input(shape=(TrainingPadShape, ))
modelLayers = Embedding(VocabSize +1, DimentionEmbeddingLayer)(inputLayer) # Vocabsize + 1 as indexing starts from 0
modelLayers = LSTM(DimentionLSTMLayer, return_sequences=True)(modelLayers)
modelLayers = GlobalMaxPooling1D()(modelLayers)
modelLayers = Dense(64, activation="relu")(modelLayers)
modelLayers = Dense(3, activation="softmax")(modelLayers)

model = Model(inputLayer, modelLayers)

2023-02-27 11:12:19.754420: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-27 11:12:19.754647: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-27 11:12:19.754667: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (adamo-Surface-Pro-7): /proc/driver/nvidia/version does not exist
2023-02-27 11:12:19.755165: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Compling the model

In [57]:
model.compile(optimizer="RMSprop",loss="CategoricalCrossentropy",metrics=["accuracy"])

## Fitting data

In [58]:
# fittingdata= model.fit(train_padded, y_train, epochs=1,validation_data=(test_padded, y_test))

### Tesing tracking weights

In [59]:
from keras.callbacks import ModelCheckpoint

In [60]:
checkpoint1 = ModelCheckpoint("Final_model.hdf5", monitor='val_accuracy', verbose=1,save_best_only=True, mode='auto', period=1,save_weights_only=False)
history = model.fit(train_padded, y_train, epochs=100,validation_data=(test_padded, y_test),callbacks=[checkpoint1])

Epoch 1/100
3565/3565 [==============================] - ETA: 0s - loss: 0.5898 - accuracy: 0.7682
Epoch 1: val_accuracy improved from -inf to 0.85842, saving model to Final_model.hdf5
3565/3565 [==============================] - 31s 8ms/step - loss: 0.5898 - accuracy: 0.7682 - val_loss: 0.4240 - val_accuracy: 0.8584
Epoch 2/100
3565/3565 [==============================] - ETA: 0s - loss: 0.3991 - accuracy: 0.8708
Epoch 2: val_accuracy improved from 0.85842 to 0.87223, saving model to Final_model.hdf5
3565/3565 [==============================] - 30s 8ms/step - loss: 0.3991 - accuracy: 0.8708 - val_loss: 0.3991 - val_accuracy: 0.8722
Epoch 3/100
3563/3565 [============================>.] - ETA: 0s - loss: 0.3773 - accuracy: 0.8797
Epoch 3: val_accuracy improved from 0.87223 to 0.87437, saving model to Final_model.hdf5
3565/3565 [==============================] - 30s 8ms/step - loss: 0.3772 - accuracy: 0.8798 - val_loss: 0.3977 - val_accuracy: 0.8744
Epoch 4/100
3560/3565 [==============

3565/3565 [==============================] - 32s 9ms/step - loss: 0.3287 - accuracy: 0.9008 - val_loss: 0.4367 - val_accuracy: 0.8739
Epoch 29/100
3561/3565 [============================>.] - ETA: 0s - loss: 0.3284 - accuracy: 0.9013
Epoch 29: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 31s 9ms/step - loss: 0.3284 - accuracy: 0.9013 - val_loss: 0.4240 - val_accuracy: 0.8709
Epoch 30/100
3559/3565 [============================>.] - ETA: 0s - loss: 0.3285 - accuracy: 0.9011
Epoch 30: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 31s 9ms/step - loss: 0.3286 - accuracy: 0.9011 - val_loss: 0.4293 - val_accuracy: 0.8697
Epoch 31/100
3561/3565 [============================>.] - ETA: 0s - loss: 0.3299 - accuracy: 0.9017
Epoch 31: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 31s 9ms/step - loss: 0.3299 - accuracy: 0.9017 - val_loss: 0.4234 - val_accuracy: 0.8728
Epoch 32

3560/3565 [============================>.] - ETA: 0s - loss: 0.3270 - accuracy: 0.9041
Epoch 57: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 34s 9ms/step - loss: 0.3269 - accuracy: 0.9041 - val_loss: 0.4787 - val_accuracy: 0.8674
Epoch 58/100
3561/3565 [============================>.] - ETA: 0s - loss: 0.3262 - accuracy: 0.9041
Epoch 58: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 35s 10ms/step - loss: 0.3262 - accuracy: 0.9041 - val_loss: 0.4830 - val_accuracy: 0.8664
Epoch 59/100
3565/3565 [==============================] - ETA: 0s - loss: 0.3275 - accuracy: 0.9042
Epoch 59: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 32s 9ms/step - loss: 0.3275 - accuracy: 0.9042 - val_loss: 0.5060 - val_accuracy: 0.8672
Epoch 60/100
3562/3565 [============================>.] - ETA: 0s - loss: 0.3274 - accuracy: 0.9039
Epoch 60: val_accuracy did not improve from 0.87844
35

Epoch 86/100
3565/3565 [==============================] - ETA: 0s - loss: 0.3364 - accuracy: 0.9041
Epoch 86: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 32s 9ms/step - loss: 0.3364 - accuracy: 0.9041 - val_loss: 0.5364 - val_accuracy: 0.8610
Epoch 87/100
3563/3565 [============================>.] - ETA: 0s - loss: 0.3363 - accuracy: 0.9050
Epoch 87: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 32s 9ms/step - loss: 0.3364 - accuracy: 0.9049 - val_loss: 0.5287 - val_accuracy: 0.8599
Epoch 88/100
3560/3565 [============================>.] - ETA: 0s - loss: 0.3371 - accuracy: 0.9043
Epoch 88: val_accuracy did not improve from 0.87844
3565/3565 [==============================] - 32s 9ms/step - loss: 0.3370 - accuracy: 0.9043 - val_loss: 0.5093 - val_accuracy: 0.8570
Epoch 89/100
3563/3565 [============================>.] - ETA: 0s - loss: 0.3360 - accuracy: 0.9047
Epoch 89: val_accuracy did not improve fro

## Load model two

In [61]:
# Load model as model
from tensorflow import keras
model = keras.models.load_model('Final_model.hdf5')

## Evalutating model

In [62]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 31)]              0         
                                                                 
 embedding (Embedding)       (None, 31, 10)            179550    
                                                                 
 lstm (LSTM)                 (None, 31, 30)            4920      
                                                                 
 global_max_pooling1d (Globa  (None, 30)               0         
 lMaxPooling1D)                                                  
                                                                 
 dense (Dense)               (None, 64)                1984      
                                                                 
 dense_1 (Dense)             (None, 3)                 195       
                                                             

In [63]:
score = model.evaluate(test_padded, y_test)
print("Model Loss: ", score[0])
print("Model accuracy", score[1])

1528/1528 [==============================] - 5s 3ms/step - loss: 0.3898 - accuracy: 0.8784
Model Loss:  0.3898230791091919
Model accuracy 0.8784438967704773


## Predicting data

In [64]:
def predict_sentiment(text):
    text_sequence = tokenizer.texts_to_sequences(text)

    text_padded = pad_sequences(text_sequence, maxlen=TrainingPadShape)

    predicted_sentiment = model.predict(text_padded)
    if predicted_sentiment[0][0] > predicted_sentiment[0][1] and predicted_sentiment[0][0] > predicted_sentiment[0][2]:
        print("Negative")
    elif predicted_sentiment[0][1] > predicted_sentiment[0][0] and predicted_sentiment[0][1] > predicted_sentiment[0][2]:
        print("Neutral")
    else:
        print("Positive")

In [65]:
text = []
userinput = input("Text to test sentiment... ")
text.append(userinput)
predicted = predict_sentiment(text)

Text to test sentiment... magical
1/1 [==============================] - 0s 379ms/step
Positive


In [66]:
text = ['Today I have had such a productive day! I watered the plants and went to the gym.']
predict_sentiment(text)

1/1 [==============================] - 0s 26ms/step
Negative


In [67]:
text = ['Done nothing, not feeling great, need a sleep.']
predict_sentiment(text)

1/1 [==============================] - 0s 20ms/step
Positive


In [68]:
text = ['Mathieu Debuchy']
predict_sentiment(text)

1/1 [==============================] - 0s 21ms/step
Neutral


In [69]:
text = ['Bad day']
predict_sentiment(text)

1/1 [==============================] - 0s 19ms/step
Negative


In [70]:
text = ['WHAT A WIN']
predict_sentiment(text)

1/1 [==============================] - 0s 25ms/step
Positive


In [71]:
text = ['Drone war 1']
predict_sentiment(text)

1/1 [==============================] - 0s 25ms/step
Neutral
