# Second dataset

## Get Data

In [21]:
import pandas as pd

In [22]:
dfcsv = pd.read_csv("../Twitter_Data.csv")

In [23]:
dfcsv.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [24]:
dfcsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   clean_text  162976 non-null  object 
 1   category    162973 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.5+ MB


In [25]:
dfcsv.isnull().sum()

clean_text    4
category      7
dtype: int64

## Data cleansing

In [26]:
import tensorflow as tf
import numpy as np
import re

2023-02-17 16:58:39.136972: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-17 16:58:39.250884: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-17 16:58:39.254388: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-17 16:58:39.254398: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if yo

### Remove null values 

In [27]:
dfcsv.dropna(inplace=True) # removes rows with null values

In [28]:
dfcsv.isnull().sum()

clean_text    0
category      0
dtype: int64

In [29]:
import re
# Same cleaning function as other dataset
def clean_data(text):
    # Removing mentions
    text = re.sub(r"/b@","",text)
        
    # Remove links
    text = re.sub(r"(?:\@|https?\://)\S+", "", text)
    
    # Remove digits & strings of digits
    text = re.sub(r"([0-9])","",text)
    
    # Remove new lines
    text = re.sub(r"\n","",text)
    
    # Removes all punctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    
    return text

In [30]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(clean_data)

In [31]:
dfcsv.head()

clean_text  category
0  when modi promised minimum government maximum ...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

## Lowercase text

In [32]:
def lowercase_data(data):
    data = data.lower()
    return data

In [33]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lowercase_data)

In [34]:
dfcsv.head(10)

clean_text  category
0  when modi promised minimum government maximum ...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0
5           kiya tho refresh maarkefir comment karo        0.0
6  surat women perform yagna seeks divine grace f...       0.0
7  this comes from cabinet which has scholars lik...       0.0
8  with upcoming election india saga going import...       1.0
9                         gandhi was gay does modi         1.0

## Remove emojis

In [35]:
def remove_emoji(data):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  #face emojis
                           u"\U0001F300-\U0001F5FF"  #symbols
                           u"\U0001F680-\U0001F6FF"  #transport & map emojis
                           u"\U0001F1E0-\U0001F1FF"  # flags
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', data)

In [36]:
remove_emoji("🇬🇧")

''

In [37]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lowercase_data)

In [38]:
dfcsv.head(10)

clean_text  category
0  when modi promised minimum government maximum ...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0
5           kiya tho refresh maarkefir comment karo        0.0
6  surat women perform yagna seeks divine grace f...       0.0
7  this comes from cabinet which has scholars lik...       0.0
8  with upcoming election india saga going import...       1.0
9                         gandhi was gay does modi         1.0

## Remove Stop words

In [39]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /home/adamo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [40]:
from nltk.corpus import stopwords
stopwords = stopwords.words("english")

In [41]:
print(stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [42]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lambda words: ' '.join([word for word in words.split() if word not in (stopwords)]))
# Using lamba to have a neat inline function, also works better than using a written function

In [43]:
dfcsv.head(10)

clean_text  category
0  modi promised minimum government maximum gover...      -1.0
1             talk nonsense continue drama vote modi       0.0
2  say vote modi welcome bjp told rahul main camp...       1.0
3  asking supporters prefix chowkidar names modi ...       1.0
4  answer among powerful world leader today trump...       1.0
5            kiya tho refresh maarkefir comment karo       0.0
6  surat women perform yagna seeks divine grace n...       0.0
7  comes cabinet scholars like modi smriti hema t...       0.0
8  upcoming election india saga going important p...       1.0
9                                    gandhi gay modi       1.0

## Removing non enlgish words

In [44]:
nltk.download("words")

[nltk_data] Downloading package words to /home/adamo/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [45]:
Allwords = set(nltk.corpus.words.words())

In [46]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lambda w: ' '.join([ws for ws in w.split() if ws in (Allwords) or not ws.isalpha()]))

In [47]:
dfcsv.head(10)

clean_text  category
0  minimum government maximum governance begin di...      -1.0
1                  talk nonsense continue drama vote       0.0
2  say vote welcome told main campaigner think relax       1.0
3  prefix great service confusion read crustal cl...       1.0
4  answer among powerful world leader today trump...       1.0
5                           tho refresh comment karo       0.0
6                  surat perform divine grace become       0.0
7          comes cabinet like smriti time introspect       0.0
8  upcoming election saga going important pair lo...       1.0
9                                                gay       1.0

## Lemmatization

In [48]:
import nltk 
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to /home/adamo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/adamo/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [49]:
from nltk.stem import WordNetLemmatizer

In [50]:
lemmatizer = WordNetLemmatizer()

In [51]:
print(lemmatizer.lemmatize("dogs"))
print(lemmatizer.lemmatize("phones"))

dog
phone


In [52]:
dfcsv["clean_text"] = dfcsv["clean_text"].apply(lemmatizer.lemmatize)

In [53]:
dfcsv.head(10)

clean_text  category
0  minimum government maximum governance begin di...      -1.0
1                  talk nonsense continue drama vote       0.0
2  say vote welcome told main campaigner think relax       1.0
3  prefix great service confusion read crustal cl...       1.0
4  answer among powerful world leader today trump...       1.0
5                           tho refresh comment karo       0.0
6                  surat perform divine grace become       0.0
7          comes cabinet like smriti time introspect       0.0
8  upcoming election saga going important pair lo...       1.0
9                                                gay       1.0

## Encoding the label

In [54]:
def sentiment_encoder(data):
    if data == -1.0:
        data = 0
    elif data == 1.0:
        data = 2
    elif data == 0:
        data = 1
    else:
        data = None
        
    return data

In [55]:
dfcsv["category"] = dfcsv["category"].apply(sentiment_encoder)

In [56]:
dfcsv.head()

clean_text  category
0  minimum government maximum governance begin di...         0
1                  talk nonsense continue drama vote         1
2  say vote welcome told main campaigner think relax         2
3  prefix great service confusion read crustal cl...         2
4  answer among powerful world leader today trump...         2

In [57]:
dfcsv.isnull().sum()

clean_text    0
category      0
dtype: int64

## Split data into training and testing

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
# Test size is 30% of total data from data set
x_train, x_test, y_train, y_test = train_test_split(dfcsv["clean_text"].values, dfcsv["category"].values,
                                                    test_size=0.3)

# Checking the sentiment has been split up appropriately 
print('sentiment Text: ', x_train[2])
print('sentiment: ', y_train[2])

sentiment Text:  three left polling much team responsible farmer distress take today economic times set global best
sentiment:  2


## Tokenizing data

In [60]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [61]:
tokenizer = Tokenizer(num_words=100000000)
totalWords = [*x_train, *x_test]
tokenizer.fit_on_texts(totalWords)

In [62]:
wordindex = tokenizer.word_index
VocabSize= len(wordindex)
print("The number of unique words is: ", VocabSize)

The number of unique words is:  17954


In [63]:
print(wordindex)

{'people': 1, 'congress': 2, 'like': 3, 'one': 4, 'vote': 5, 'dont': 6, 'country': 7, 'election': 8, 'time': 9, 'even': 10, 'nation': 11, 'also': 12, 'know': 13, 'government': 14, 'get': 15, 'power': 16, 'want': 17, 'minister': 18, 'give': 19, 'good': 20, 'space': 21, 'would': 22, 'said': 23, 'money': 24, 'see': 25, 'done': 26, 'credit': 27, 'party': 28, 'make': 29, 'sir': 30, 'prime': 31, 'every': 32, 'think': 33, 'say': 34, 'take': 35, 'back': 36, 'never': 37, 'work': 38, 'support': 39, 'opposition': 40, 'via': 41, 'new': 42, 'many': 43, 'need': 44, 'come': 45, 'made': 46, 'today': 47, 'poor': 48, 'please': 49, 'world': 50, 'last': 51, 'great': 52, 'much': 53, 'media': 54, 'may': 55, 'anti': 56, 'right': 57, 'win': 58, 'news': 59, 'leader': 60, 'first': 61, 'political': 62, 'well': 63, 'still': 64, 'day': 65, 'best': 66, 'going': 67, 'live': 68, 'satellite': 69, 'better': 70, 'mission': 71, 'man': 72, 'way': 73, 'family': 74, 'cant': 75, 'got': 76, 'must': 77, 'given': 78, 'nothing':

In [64]:
import json
fileToDump = open("Embeddings.json","w")

json.dump(wordindex,fileToDump)

fileToDump.close()

In [65]:
len(x_test)

48891

In [66]:
train_seq = tokenizer.texts_to_sequences(x_train) # Compares all the data to vocab and assigns a integer reference for the vocab 
test_seq = tokenizer.texts_to_sequences(x_test)
print(test_seq)

[[401, 2068, 33, 107, 304, 34, 1548, 438, 29, 289, 13, 75, 890, 1123, 441, 169, 1501, 1486, 3451, 1033], [468, 618, 207, 312], [17, 13, 258, 1575, 1439], [611, 236, 4, 499, 5900, 1682, 4198, 425, 247, 1248, 3396, 1446, 2725, 514, 502, 5159, 508, 247, 72, 818, 2041, 338], [526, 11, 11], [1157, 332, 237, 684, 3352, 1379, 2251, 2932, 4188, 7], [1387, 3316], [19, 94, 256, 151, 330, 148, 759, 1388, 716], [25, 1660, 5407, 4834, 209, 2819, 853, 1062, 13296, 1657, 250, 282, 358], [8, 89], [1399, 780, 239, 19, 81, 1184, 239, 213], [54, 53, 1944, 4128], [34, 714], [329, 906, 30, 279, 21, 71, 117, 112, 1069, 576, 285, 1162, 21, 11884, 155], [189, 128, 386, 2112, 771, 290, 1681, 1505, 128, 115, 196, 16], [167, 185, 112], [52, 193, 242], [1, 168, 847], [141, 907, 24, 711, 251, 141, 1923, 5701, 4334, 141, 116, 1150, 116, 90, 1150], [63, 23, 72, 1373, 51, 2078, 3252, 3089, 1316, 66, 655, 1316, 26, 57, 73, 969, 969], [1246, 1968, 10, 818], [45, 16, 2456, 247, 300, 727, 698], [90, 142, 17, 45, 65, 479]

In [67]:
len(test_seq)

48891

In [68]:
from tensorflow.keras.preprocessing.sequence import pad_sequences 

In [69]:
# PAD sequences so they are all the same length as the inputs must all be of same length

train_padded = pad_sequences(train_seq)

print(train_padded[0])

# Check size of each padded sequence

TrainingPadShape = train_padded.shape[1] # for use when defining the model shape 
print(TrainingPadShape)

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0  91 129 411 932  12 219  88]
31


In [70]:
test_padded = pad_sequences(test_seq,maxlen=TrainingPadShape)
print(test_padded.shape[1])

31


In [71]:
print(y_train)

[1 0 2 ... 1 2 1]


# Data changes

In [72]:
from keras.utils import to_categorical

In [73]:
y_train = to_categorical(y_train, 3)
y_test = to_categorical(y_test, 3)

In [74]:
print(y_train)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


## Constructing the model

In [54]:
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, GlobalMaxPooling1D
from tensorflow.keras.models import Model

In [55]:
DimentionEmbeddingLayer = 10
DimentionLSTMLayer = 30

inputLayer = Input(shape=(TrainingPadShape, ))
modelLayers = Embedding(VocabSize +1, DimentionEmbeddingLayer)(inputLayer) # Vocabsize + 1 as indexing starts from 0
modelLayers = LSTM(DimentionLSTMLayer, return_sequences=True)(modelLayers)
modelLayers = GlobalMaxPooling1D()(modelLayers)
modelLayers = Dense(64, activation="relu")(modelLayers)
modelLayers = Dense(3, activation="softmax")(modelLayers)

model = Model(inputLayer, modelLayers)

2022-11-24 12:01:13.714005: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-11-24 12:01:13.714027: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-11-24 12:01:13.714046: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (adamo-Surface-Pro-7): /proc/driver/nvidia/version does not exist
2022-11-24 12:01:13.714210: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Compling the model

In [56]:
model.compile(optimizer="RMSprop",loss="CategoricalCrossentropy",metrics=["accuracy"])

## Fitting data

In [57]:
fittingdata= model.fit(train_padded, y_train, epochs=1,validation_data=(test_padded, y_test))

3565/3565 [==============================] - 31s 8ms/step - loss: 0.5826 - accuracy: 0.7702 - val_loss: 0.4350 - val_accuracy: 0.8582


### Tesing tracking weights

In [58]:
from keras.callbacks import ModelCheckpoint

In [59]:
checkpoint1 = ModelCheckpoint("Final_model.hdf5", monitor='val_accuracy', verbose=1,save_best_only=True, mode='auto', period=1,save_weights_only=False)
history = model.fit(train_padded, y_train, epochs=25,validation_data=(test_padded, y_test),callbacks=[checkpoint1])

Epoch 1/25
3563/3565 [============================>.] - ETA: 0s - loss: 0.3976 - accuracy: 0.8708
Epoch 1: val_accuracy improved from -inf to 0.87171, saving model to Final_model.hdf5
3565/3565 [==============================] - 30s 8ms/step - loss: 0.3974 - accuracy: 0.8709 - val_loss: 0.4014 - val_accuracy: 0.8717
Epoch 2/25
3560/3565 [============================>.] - ETA: 0s - loss: 0.3719 - accuracy: 0.8808
Epoch 2: val_accuracy improved from 0.87171 to 0.87576, saving model to Final_model.hdf5
3565/3565 [==============================] - 30s 8ms/step - loss: 0.3720 - accuracy: 0.8808 - val_loss: 0.3903 - val_accuracy: 0.8758
Epoch 3/25
3559/3565 [============================>.] - ETA: 0s - loss: 0.3600 - accuracy: 0.8857
Epoch 3: val_accuracy improved from 0.87576 to 0.87634, saving model to Final_model.hdf5
3565/3565 [==============================] - 30s 8ms/step - loss: 0.3602 - accuracy: 0.8856 - val_loss: 0.3916 - val_accuracy: 0.8763
Epoch 4/25
3559/3565 [==================

## Load model two

In [75]:
# Load model as model
from tensorflow import keras
model = keras.models.load_model('Final_model.hdf5')

2023-02-17 16:58:59.928071: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-17 16:58:59.928093: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-17 16:58:59.928108: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (adamo-Surface-Pro-7): /proc/driver/nvidia/version does not exist
2023-02-17 16:58:59.928299: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Evalutating model

In [76]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 31)]              0         
                                                                 
 embedding (Embedding)       (None, 31, 10)            179550    
                                                                 
 lstm (LSTM)                 (None, 31, 30)            4920      
                                                                 
 global_max_pooling1d (Globa  (None, 30)               0         
 lMaxPooling1D)                                                  
                                                                 
 dense (Dense)               (None, 64)                1984      
                                                                 
 dense_1 (Dense)             (None, 3)                 195       
                                                             

In [77]:
score = model.evaluate(test_padded, y_test)
print("Model Loss: ", score[0])
print("Model accuracy", score[1])

1528/1528 [==============================] - 4s 2ms/step - loss: 0.9624 - accuracy: 0.7130
Model Loss:  0.9624007940292358
Model accuracy 0.7129942178726196


## Predicting data

In [89]:
def predict_sentiment(text):
    text_sequence = tokenizer.texts_to_sequences(text)

    text_padded = pad_sequences(text_sequence, maxlen=TrainingPadShape)

    predicted_sentiment = model.predict(text_padded)
    if predicted_sentiment[0][0] > predicted_sentiment[0][1] and predicted_sentiment[0][0] > predicted_sentiment[0][2]:
        print("Negative")
    elif predicted_sentiment[0][1] > predicted_sentiment[0][0] and predicted_sentiment[0][1] > predicted_sentiment[0][2]:
        print("Neutral")
    else:
        print("Positive")

In [90]:
text = []
userinput = input("Text to test sentiment... ")
text.append(userinput)
predicted = predict_sentiment(text)

Text to test sentiment... hello
1/1 [==============================] - 0s 15ms/step
Neutral


In [88]:
text = ['Today I have had such a productive day! I watered the plants and went to the gym.']
predict_sentiment(text)

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,    47,  3714,
           65, 10026,   363, 11872]], dtype=int32)

In [68]:
text = ['Done nothing, not feeling great, need a sleep.']
predict_sentiment(text)

1/1 [==============================] - 0s 19ms/step
Positive


In [69]:
text = ['Mathieu Debuchy']
predict_sentiment(text)

1/1 [==============================] - 0s 19ms/step
Neutral


In [70]:
text = ['Bad day']
predict_sentiment(text)

1/1 [==============================] - 0s 19ms/step
Negative


In [71]:
text = ['WHAT A WIN']
predict_sentiment(text)

1/1 [==============================] - 0s 20ms/step
Positive


In [72]:
text = ['Drone war 1']
predict_sentiment(text)

1/1 [==============================] - 0s 21ms/step
Neutral
